before_build:
  - nuget restore

build:
  verbosity: minimal
after_build:
- cmd: "if %APPVEYOR_REPO_BRANCH% == master "D:\GitHub\HTTP-Server\packages\Tools.InnoSetup.5.5.6\tools\ISCC.exe" "D:\GitHub\HTTP-Server\InstallScript.iss""
  
# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"

artifacts:
  - path: HTTP-Server\bin\$(configuration)
    name: HTTP-Server
    
