before_build:
  - nuget restore
  - ps: >-
    if($env:APPVEYOR_REPO_BRANCH -eq "master"){

    if($env:APPVEYOR_REPO_TAG){

    $env:CONFIGURATION = "Release"

    Write-Host "Switch to Release configuration"

    }

    else{

    $env:CONFIGURATION = "Debug"

    Write-Host "Switch to Debug configuration"

    }

    }
build:
  verbosity: minimal
after_build:
- cmd: "if %APPVEYOR_REPO_BRANCH% == master \n\"D:\\GitHub\\HTTP-Server\\packages\\Tools.InnoSetup.5.5.6\\tools\\ISCC.exe\" \n\"D:\\GitHub\\HTTP-Server\\InstallScript.iss\""
  
# enable patching of AssemblyInfo.* files
assembly_info:
  patch: true
  file: AssemblyInfo.*
  assembly_version: "1.0.0.{build}"
  assembly_file_version: "{version}"
  assembly_informational_version: "{version}"
  
artifacts:
  - path: HTTP-Server\bin\$(configuration)
    name: HTTP-Server
    
